[MovieConfig]

;country = CHN
;country = JAP
;country = KOR
country = WEST
;country = SLA
;country = SEA
;country = LTA

;actor = Anna


;movie = Test
;year = 2009
source_file_path = D:\迅雷下载\[R]\[2009]test.mkv
;season = 1
;episode = 9


;target_base_path = F:\DB\影视\Clip\待整理
target_base_path = D:\ffmpeg

